# Generated by Django 4.2 on 2023-04-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=20, unique=True)),
                ('sexo', models.CharField(max_length=10)),
                ('data_nascimento', models.DateField()),
                ('habilitacao', models.BooleanField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carga_horaria_semanal', models.IntegerField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('horas_necessarias', models.IntegerField()),
                ('prazo_estimado', models.DateField()),
                ('horas_realizadas', models.IntegerField(default=0)),
                ('ultimo_calculo_horas', models.DateField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.departamento')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_trabalhadas', models.IntegerField()),
                ('horas_supervisao', models.IntegerField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.funcionario')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.projeto')),
            ],
        ),
    ]
